---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  rules:
  — host: ""
    http:
      paths:
      — backend:
          serviceName: wordpress
          servicePort: 80
